spring:
  web:
    resources:
      static-locations:
      - classpath:/static/
      - file:/static/img/
  datasource:
    url: jdbc:postgresql://localhost:5432/ota
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
