spring:
  web:
    resources:
      static-locations:
      - classpath:/static/
      - file:/static/img/
  datasource:
    url: jdbc:postgresql://localhost:5432/ota
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ryoto.noguchi@gmail.com
    password: npovkduzdtvzwuid
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: false
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.trust: smtp.gmail.com

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
