# server:
#   port: 5000
spring:
  # profiles:
  #   active: @spring.profiles.active@
  web:
    resources:
      static-locations:
      - classpath:/static/
      - file:/static/img/
  datasource:
    # ↓ローカル上のPostgres
    # url: jdbc:postgresql://localhost:5432/ota
    # ↓Docker上のPostgres
    # url: jdbc:postgresql://localhost:5432/postgres
    # ↓AWS(RDS)上のPostgres
    url: jdbc:postgresql://portfolio-ota-db.clgrhvnsnncj.ap-northeast-1.rds.amazonaws.com:5432/otademo
    username: postgres
    password: postgres
    # ↓Docker上のPostgres
    # password: password
    sql-script-encoding: UTF-8
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ryoto.noguchi@gmail.com
    password: npovkduzdtvzwuid
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: false
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.trust: smtp.gmail.com

stripe:
  keys:
    public: pk_test_51I8E5wE3yhgepcJZTZN4tFuMIyiOiXGCU0ScD0UkNkmcrj9uYhoZRBGHTKRqXB4i4D8PED7MvL7GJI9nnOFcOQQr002DtSIWWW
    secret: sk_test_51I8E5wE3yhgepcJZ2fECdvZGYh7I8QPdRfcRfyS9Ytldn9ltbVcibugxMMx6QSlkvra4BxXDHwuV1IpG14V3QSfe00ojDxY8eX

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
