spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ota
    username: postgres
    password: postgres
    sql-script-encoding: UTF-8
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 214571143579891
            client-secret: 559df366fccd477e3330c45f58fd74ee
            # scope:


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
